services:
  qmlros2:
    image: qmlros2:humble
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    network_mode: host
    working_dir: /ws
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOST_SRC:-$HOME/Documents/Aelleek/qml_ros2_plugin}:/ws/src/qml_ros2_plugin:rw
    command: >
      bash -lc "source /opt/ros/humble/setup.bash &&
                colcon build --symlink-install &&
                source install/setup.bash &&
                bash"
