name: CI
on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]

jobs:
  linting:
    runs-on: ubuntu-20.04
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-foxy-ros-base-latest
#      options: -u root  # setup-node requires root access
    strategy:
      matrix:
        linter:
          - name: lint_cmake
          - name: clang-format
            args: --config .clang-format
          - name: cppcheck
            args: --language c++
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/action-ros-lint@v0.1
        with:
          linter: ${{ matrix.linter.name }}
          arguments: ${{ matrix.linter.args }}
          package-name: qml_ros2_plugin
  testing-and-coverage:
    needs: linting
    runs-on: ${{ matrix.setup.os }}
    strategy:
      matrix:
        setup:
          - os: ubuntu-20.04
            ros_distribution: foxy
          - os: ubuntu-21.04
            ros_distribution: galactic
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ matrix.setup.ros_distribution }}
      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          import-token: ${{ secrets.GITHUB_TOKEN }}
          package-name: qml_ros2_plugin
          target-ros2-distro: ${{ matrix.setup.ros_distribution }}
          vcs-repo-file-url: .github/workflows/deps.repos
      - uses: ros-tooling/action-ros-lint@v0.1
        with:
          linter: clang-tidy
          package-name: qml_ros2_plugin
